MDScreen:
    canvas:
        Color:
            rgba: (1,1,1,1)
        Rectangle:
            size: (1500,1500)
            pos: self.pos
    # Set screen name
    name: "hide"
    # Add box layout
    BoxLayout:
        orientation: 'vertical'
        Label:
            id:one
            text:""
        Label:
            id:two
            text:""
        Label:
            id:three
            text:""